# Continue Extension Configuration for Local MCP Hub
# Place this content in your Continue extension config.yaml file

models:
  - name: "Local MCP Hub + Qwen2.5"
    provider: openai
    model: "qwen2.5:latest" 
    apiBase: "http://localhost:3002/v1"
    apiKey: "dummy-key"
    requestOptions:
      headers:
        "User-Agent": "Continue-VSCode"
    roles:
      - chat
      - edit
      - apply
      - autocomplete
    capabilities:
      - tool_use
    supportsToolUse: true
    defaultCompletionOptions:
      temperature: 0.2
      maxTokens: 4000

tabAutocompleteModel:
  name: "Local MCP Hub + Qwen2.5 Autocomplete"
  provider: openai
  model: "qwen2.5:latest"
  apiBase: "http://localhost:3002/v1"
  apiKey: "dummy-key"
  requestOptions:
    headers:
      "User-Agent": "Continue-VSCode-Autocomplete"

tabAutocompleteOptions:
  multilineCompletions: "always"
  maxPromptTokens: 4000
  debounceDelay: 300

contextProviders:
  - name: http
    params:
      url: "http://localhost:3002/health"
      description: "Local MCP Hub Health Check"

agents:
  - name: "MCP Agent"
    model: "Local MCP Hub + Qwen2.5"
    systemMessage: |
      You are an autonomous agent with access to tools via MCP servers.
      You can read files, execute commands, and perform various development tasks.
      Always explain what you're doing and ask for confirmation before making significant changes.

experimental:
  enableAgentMode: true

allowAnonymousTelemetry: false
